//
//  String.swift
//  FlowerApp


import Foundation


struct STRING {
    static let errorPassword = "Please enter password"
    static let errorValidPassword = "Please enter valid password"
    static let errorEmail = "Please enter email"
    static let errorValidEmail = "Please enter valid email"
    static let errorEnterName = "Please enter name"
    static let errorMobile = "Please enter mobile number"
    static let errorValidMobile = "Please enter valid mobile number"
    static let errorOType = "Please enter organisation type"
    static let errorOccupation = "Please enter occupation"
    static let errorOName = "Please enter organisation name"
    static let errorConfirmPassword = "Please enter confirm password"
    static let errorPasswordMismatch = "Password mismatch"
    static let errorCheckBox = "Please agree to terms and conditions"
    static let errorValidCreatePassword = "Password must contain (1upper 1lower 1special 1numeric)"
    static let errorPasswordCount = "Please enter password with atleast 8 characters"
    static let errorAddress = "Please enter address"
    static let errorEducationLevel = "Please enter education level"
    static let errorJobExp = "Please enter job experience"
    static let errorSkills = "Please enter skills"
    static let errorAboutMe = "Please enter about me"
    static let errorEnterJobName = "Please enter job name"
    static let errorEnterJobAddress = "Please enter job address"
    static let errorEnterJobEmail = "Please enter job email"
    static let errorEnterJobSalary = "Please enter job salary"
    static let errorEnterJobDescription = "Please enter job description"
    static let errorEnterJobRequirement = "Please enter job requirement"
}

let jUser           = "jk_users"
let jUID            = "uid"
let jProfileData    = "profile"
let jName           = "empName"
let jEmail          = "email"
let jPhone          = "empPhone"
let jIsBlock        = "isBlocked"
let jOrgType        = "orgType"
let jOrgName        = "orgName"
let jOrgLocation    = "orgLocation"
let jOrgAddress     = "orgAddress"
let jOrgImageURL    = "orgImageUrl"
let jSkills         = "jsSkills"
let jJSPhone        = "jsPhone"
let jJSImageURL     = "jsImageUrl"
let jJSEduLevel     = "jsEduLevel"
let jJSAddress      = "jsAddress"
let jJSAboutMe      = "jsAboutMe"
let jOccupation     = "jsOccupation"
let jJSName         = "jsName"
let jJSLocation     = "jsLocation"
let jJSExp          = "jsJobXp"
let jUserType       = "userType"
let jCity           = "city"
let jState          = "state"
let jZipcode        = "zipcode"
let jPassword       = "password"
let jImage          = "imagePath"
let jDescription    = "description"
let docID           = "docID"
let jFavourite      = "favourite"
let jOrder          = "order"
let jOrderDate      = "orderDate"
let jOrderType      = "orderType"
let jJobs           = "jobs"
let jJobSave        = "savedJobs"
let jJobAddress     = "jobAddress"
let jPostName       = "jobName"
let jJobOType       = "job_oType"
let jJobEmail       = "jobEmail"
let jAddress        = "address"
let jJobSalary      = "salaryPerHr"
let jRequirement    = "jobRequirements"
let jJobDescription = "jobDescription"
let jUserEmail      = "user_email"
let jFavID          = "fav_id"
let jIsApproved     = "isApproved"
let jIsRejected     = "isRejected"
let jJobID          = "jobID"
let jLocation       = "jobLocation"
let jApplyJobs      = "appliedJobs"
let jEmpEmail       = "empEmail"
let jsSavedAndApplied = "jsSavedAndApplied"
let isApplied = "isApplied"
let isSaved = "isSaved"
let jsEmail = "jsEmail"


let jEmp        = "Employer"
let jJSeeker    = "JobSeeker"
